apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: fluent-bit
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::714771635465:role/dev-fluent-bit-iam-role
  name: fluent-bit
  namespace: logging
